service: icompaas
provider:
 name: aws
 runtime: python3.10
 stage: dev
 region: ap-south-1
 memorySize: 128
plugins:
 - serverless-wsgi
 - serverless-python-requirements
custom:
 wsgi:
   app: app.app
   packRequirements: false
functions:
 app:
   handler: wsgi.handler
   events:
     - http: ANY /
     - http: 'ANY {proxy+}'
